name: spendwise_models
description: common models for spendwise.
version: 0.1.2+6
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  freezed_annotation: 
  json_annotation: 
  
dev_dependencies:
  build_runner:
  freezed:
  json_serializable: 