name: spendwise_models
description: models for spendwise.
version: 0.1.0+2
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  # hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  
dev_dependencies:
  build_runner:
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  hive_generator:
